export const UPDATE = "UPDATE";
export const CREATE = "CREATE";
export const DELETE = "DELETE";
export const FETCH_ALL = "FETCH_ALL";
export const FETCH_ALL_BY_PAGINATION = "FETCH_ALL_BY_PAGINATION";
export const FETCH_ALL_BY_SEARCH = "FETCH_ALL_BY_SEARCH";
export const FETCH_ALL_SORTED = "FETCH_ALL_SORTED";
export const FETCH_ALL_BY_PAGINATION_AND_CATEGORY = "FETCH_ALL_BY_PAGINATION_AND_CATEGORY";
export const RATE = "RATE";
export const DELETE_ALL_PRODUCTS = "DELETE_ALL_PRODUCTS";

export const UPDATE_CART = "UPDATE_CART";
export const CREATE_CART = "CREATE_CART";
export const DELETE_CART = "DELETE_CART";
export const FETCH_ALL_CART = "FETCH_ALL_CART";
export const FETCH_ALL_CART_BY_USER_ID = "FETCH_ALL_CART_BY_USER_ID";
export const DELETE_ALL_CART = "DELETE_ALL_CART";

export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";

export const ERROR = "ERROR";
export const NOERROR = "NOERROR";

export const FETCH_ALL_FILES = "FETCH_ALL_FILES";
export const FETCH_ALL_FILES_FIRST = "FETCH_ALL_FILES_FIRST";
export const FETCH_ALL_FILES_BY_PRODUCT_ID = "FETCH_ALL_FILES_BY_PRODUCT_ID";
export const DELETE_ALL_FILES = "DELETE_ALL_FILES";

export const FETCH_ALL_VARIANTS = "FETCH_ALL_VARIANTS";
export const FETCH_ALL_VARIANTS_BY_PRODUCT_ID = "FETCH_ALL_VARIANTS_BY_PRODUCT_ID";
export const DELETE_ALL_VARIANTS = "DELETE_ALL_VARIANTS";

export const ORDER = "ORDER";